
tls:
  certificates:
    - certFile: "/certs/wild.crt"
      keyFile: "/certs/wild.key"
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/wild.crt"
        keyFile: "/certs/wild.key"


chain-oauth:
  chain:
    middlewares:
      - middlewares-rate-limit
      - middlewares-https-redirectscheme
      - middlewares-secure-headers
      - middlewares-oauth
      - middlewares-compress