version: "3.5"

services:

  httpd:
    build:
      context: .
    container_name: httpd
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - public
    labels:
    - "traefik.http.routers.httpd.tls=true"
    - "traefik.http.services.httpd.loadbalancer.server.port=80"
    - "traefik.enable=true"
    - "traefik.http.routers.httpd.rule=Host(`httpd.${DOMAINNAME}`)"
    - "traefik.http.routers.httpd.entrypoints=web"
    - "traefik.http.routers.httpd.entrypoints=websecure"

networks:
  public:
    name: global_public
    external: true
