version: "3.5"

services:

  webclient:
    image: webclient
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.http.routers.webclient.tls=true"
        - "traefik.http.services.webclient.loadbalancer.server.port=80"
        - "traefik.enable=true"
        - "traefik.http.routers.webclient.rule=Host(`webclient.heroma.test`)"
        - "traefik.http.routers.webclient.entrypoints=web"
        - "traefik.http.routers.webclient.entrypoints=websecure"

networks:
  traefik-public:
    external: true
